name: Release

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Release?'
        required: true
        type: boolean
        default: false
      upgrade_version:
        description: 'Upgrade version before release?'
        required: true
        type: boolean
        default: true

jobs:
  upgrade:
    uses: ./.github/workflows/upgrade.yaml
    with:
      confirmation: ${{ github.event.inputs.upgrade_version }}

  release:
    needs: [ upgrade ]
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation
        run: |
          echo "Confirmation: ${{ github.event.inputs.confirmation }}"
          if [ "${{ github.event.inputs.confirmation }}" != "true" ]; then
            echo "Confirmation not checked. Skipping the release."
            exit 1
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          server-id: oss-sonatype
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
          settings-path: ${{ github.workspace }}

      - name: "Release artifacts"
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
        run: mvn deploy --settings $GITHUB_WORKSPACE/settings.xml -B -U -P release -DskipTests=true
