name: Release Parent POM

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'This will release the parent POM. Are you sure?'
        required: true
        type: choice
        options:
          - 'No'
          - 'Yes'
      upgrade_version:
        description: 'Should the version be upgraded before release?'
        required: true
        type: choice
        options:
          - 'No'
          - 'Yes'

jobs:
  print_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Confirmation: ${{ github.event.inputs.confirmation }}"
          echo "Upgrade version: ${{ github.event.inputs.upgrade_version }}"

  upgrade:
    uses: ./.github/workflows/upgrade.yaml
    with:
      confirmation: ${{ github.event.inputs.upgrade_version }}

  release:
    needs: [ upgrade_version ]
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" = "No" ]; then
            echo "Confirmation not checked. Skipping the release."
            exit 1
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          server-id: oss-sonatype
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
          settings-path: ${{ github.workspace }}

#      - name: "Release artifacts"
#        env:
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
#        run: mvn deploy --settings $GITHUB_WORKSPACE/settings.xml -B -U -P release -DskipTests=true
