on:
  workflow_dispatch:
    inputs:
      sdk-version: # id of input
        description: 'the version of the sdk'
        required: true
      sdk-name: # id of input
        description: 'the name of the sdk'
        required: true
jobs:
  update_bom_version:
    runs-on: ubuntu-latest
    name: Auto pom file builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: run change script
        run: bash ./start.sh
        working-directory: ./version-management
        env:
          branchName: '${{ inputs.sdk-name }}'
          sdkName: '${{ inputs.sdk-name }}'
          sdkVersion: '${{ inputs.sdk-version }}'
  deploy_bom:
    needs:  update_bom_version
    uses: ./.github/workflows/bom-release-actions.yml
    secrets: inherit

