name: Upgrade

on:
  workflow_call:
    inputs:
      confirmation:
        description: 'Should the version be upgraded before release?'
        required: true
        type: string

jobs:
  upgrade:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Check confirmation
        run: |
          echo "Confirmation: ${{ github.event.inputs.confirmation }}"
          if [ "${{ github.event.inputs.confirmation }}" = "No" ]; then
            echo "Confirmation not checked. Skipping the upgrade."
            exit 1
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Increment version
        id: increment_version
        run: |
          version=$(mvn -q \
            -Dexec.executable=echo \
            -Dexec.args='${project.version}' \
            --non-recursive \
            exec:exec)
          ((version++))
          mvn versions:set -DnewVersion=$version
          echo "version=$version" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config --global user.email "oss@expediagroup.com"
          git config --global user.name "eg-oss-ci"
          # read the version from the environment
          git commit -am "chore: upgrade POM version to ${{ env.version }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
