name: Upgrade

on:
  workflow_call:
    inputs:
      upgrade_version:
        description: 'Upgrade?'
        required: true
        type: boolean
    secrets:
      GH_PERSONAL_ACCESS_TOKEN:
        description: 'GitHub Personal Access Token'
        required: true

jobs:
  upgrade:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Check confirmation
        run: |
          if ! ${{ github.event.inputs.upgrade_version }}; then
            echo "Confirmation not checked. Skipping the upgrade."
            exit 1
          else
            echo "Confirmation checked. Proceeding with the upgrade."
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Increment version
        id: increment_version
        run: |
          version=$(mvn -q \
            -Dexec.executable=echo \
            -Dexec.args='${project.version}' \
            --non-recursive \
            exec:exec)
          ((version++))
          mvn versions:set -DnewVersion=$version
          echo "version=$version" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config --global user.email "oss@expediagroup.com"
          git config --global user.name "eg-oss-ci"
          git commit -am "chore: upgrade POM version to ${{ env.version }}"
          git add pom.xml # add this file only to the commit
          echo "branch_name=upgrade-pom-to-${{ env.version }}" >> $GITHUB_ENV
          echo "upgrade-pom-to-${{ env.version }}" > branch_name.txt

      - name: Upload branch name
        uses: actions/upload-artifact@v4
        with:
          name: branch-name
          path: branch_name.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          commit-message: "chore: upgrade POM version to ${{ env.version }}"
          title: "chore: upgrade POM version to ${{ env.version }}"
          branch: ${{ env.branch_name }}
          body: "This PR upgrades the POM version to ${{ env.version }}."
